[project]
name = "ai-data-science-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "nbclient>=0.10.2",
    "nbformat>=5.10.4",
]
